image:
  repository: gcr.io/onec-co/datamon
  tag: v2.6.8
  pullPolicy: Always

serviceAccountName: flood

# default config to map as ${HOME}/.datamon/datamon.yaml
config: |
  credential: ""
  email: ""
  name: ""
  config: global-onec-co-datamon-config
  context: staging
  metrics:
    enabled: false

command: delete-unused
force: false
dryrun: false
concurrency: 300

# the size of the volume claim to attach as download staging
stagingSize: 36Gi
storageClassName: ssd
storageType: pd-ssd

# time to live for k8 resources (in seconds)
ttl: 86400
# number of allowed job restarts upon failure (with restartPolicy: OnFailure)
backoffs: 0

# container mount points
home: '/home/project'
staging: '/data'

restartPolicy: Never
nameOverride: ""
fullnameOverride: ""
application: datamon-purge

# Tune this for maximum performances
resources: {}

nodeSelector:
  role: flood-common
tolerations:
  - key: role
    effect: NoSchedule
    operator: Equal
    value: flood-common
affinity: {}

# you may declare and mount extra volumes on the pod
extraVolumes:
extraVolumeMounts:

extraArgs: []
