run:
  build-tags:
  - fuse_cli
  - fsintegration

linters-settings:
  govet:
    check-shadowing: true
  #golint:
  #  min-confidence: 0
  gocyclo:
    min-complexity: 75
  maligned:
    suggest-new: true
  dupl:
    threshold: 300
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable-all: true
  build-tags:
    - fuse_cli
    - fsintegration
    - influxdbintegration
  disable:
    - golint
    - interfacer
    - scopelint
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
    #- golint
    - godox
    - whitespace
    - funlen
    #- stylecheck
    - unparam
    - wsl
    - gocognit
    - gomnd
    - gci
    - gofumpt
    - nlreturn
    - testpackage
    - goerr113
    - exhaustive
    - godot
    - wrapcheck
    - exhaustivestruct
    - errorlint
    - tparallel
    - nestif
    - thelper
    - tagliatelle
    - predeclared
    - paralleltest
    - ifshort
    - nilerr
    - cyclop
    - forcetypeassert
    - revive
    - forbidigo
    - gomoddirectives
    - varnamelen
    - tenv
    - nonamedreturns
    - ireturn
    - exhaustruct
    - contextcheck
    - containedctx
    - errname
    - maintidx
    - nosnakecase

max-same-issues: 0
