run:
  build-tags: fuse_cli

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 75
  maligned:
    suggest-new: true
  dupl:
    threshold: 300
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable-all: true
  build-tags:
    - fuse_cli
  disable:
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
    #- golint
    - godox
    - whitespace
    - funlen
    #- stylecheck
    - unparam
    - wsl
    - gocognit
    - gomnd
    - goprintffuncname
    - gci
    - gofumpt
    - nlreturn
    - testpackage
    - goerr113
    - exhaustive
    - godot

max-same-issues: 0
