image:
  repository: gcr.io/onec-co/datamon
  tag: hash-706c559
  pullPolicy: Always

serviceAccountName: geodude

# default config to map as ${HOME}/.datamon/datamon.yaml
config: |
  credential: ""
  email: ""
  name: ""
  config: global-onec-co-datamon-config
  context: dev
  metrics:
    enabled: false

# the size of the volume claim to attach as download staging
stagingSize: 36Gi
#storageClassName: manual # for local testing only
#storageType: local # for local testing only
storageClassName: ssd
storageType: pd-ssd
#storageClassName: standard
#storageType: pd-standard

# time to live for k8 resources (in seconds)
ttl: 86400
# number of allowed job restarts upon failure (with restartPolicy: OnFailure)
backoffs: 0

# container mount points
home: '/home/project'
staging: '/data'

restartPolicy: Never
nameOverride: ""
fullnameOverride: ""
application: datamon-purge

# Tune this for maximum performances
resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

# you may declare and mount extra volumes on the pod
extraVolumes:
extraVolumeMounts:

extraArgs: []
