image:
  repository: gcriocloudbuilders/gsutil
  tag: latest
  pullPolicy: Always

serviceAccountName: flood

path: ~

# time to live for k8 resources (in seconds)
ttl: 86400
# number of allowed job restarts upon failure (with restartPolicy: OnFailure)
backoffs: 0

restartPolicy: Never
nameOverride: ""
fullnameOverride: ""
application: gsutil-delete

# Tune this for maximum performances
resources: {}

nodeSelector:
  role: platform
tolerations:
  - key: role
    effect: NoSchedule
    operator: Equal
    value: platform
affinity: {}

# you may declare and mount extra volumes on the pod
extraVolumes:
extraVolumeMounts:

extraArgs: []
