image:
  repository: gcr.io/onec-co/datamon
  tag: v2.6.6
  pullPolicy: Always

serviceAccountName: flood

# default config to map as ${HOME}/.datamon/datamon.yaml
config: |
  credential: ""
  email: ""
  name: ""
  config: global-onec-co-datamon-config
  context: prod
  metrics:
    enabled: false

concurrency: 200
repo: inundation-schism-run-dir-backup
retaintags: false
retainsemvertags: false
nlatest: 5
loglevel: debug

# time to live for k8 resources (in seconds)
ttl: 86400
# number of allowed job restarts upon failure (with restartPolicy: OnFailure)
backoffs: 0

restartPolicy: Never
nameOverride: ""
fullnameOverride: ""
application: datamon-squash

# Tune this for maximum performances
resources: {}

nodeSelector:
  role: platform
tolerations:
  - key: role
    effect: NoSchedule
    operator: Equal
    value: platform
affinity: {}

# you may declare and mount extra volumes on the pod
extraVolumes:
extraVolumeMounts:

extraArgs: []
