#apiVersion: v1
#kind: Namespace
#metadata:
#  name: frederic-oneconcern-com

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: private-frederic-oneconcern-com
  namespace: frederic-oneconcern-com
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-frederic-oneconcern-com
  namespace: frederic-oneconcern-com
subjects:
- kind: User
  name: frederic@oneconcern.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: private-frederic-oneconcern-com
  apiGroup: rbac.authorization.k8s.io
