image:
  repository: gcr.io/onec-co/datamon
  tag: v2.6.9
  pullPolicy: Always

serviceAccountName: flood

# default config to map as ${HOME}/.datamon/datamon.yaml
config: |
  credential: ""
  email: ""
  name: ""
  config: global-onec-co-datamon-config
  context: staging
  metrics:
    enabled: false

command: build-reverse-lookup
force: true
concurrency: 150
resume: true
currentonly: true
startindex: 300

# the size of the volume claim to attach as download staging
stagingSize: 36Gi
#stagingSize: 2000Gi
#storageClassName: manual # for local testing only
#storageType: local # for local testing only
storageClassName: ssd
storageType: pd-ssd
#storageClassName: standard
#storageType: pd-standard

# time to live for k8 resources (in seconds)
ttl: 86400
# number of allowed job restarts upon failure (with restartPolicy: OnFailure)
backoffs: 0

# container mount points
home: '/home/project'
staging: '/data'

restartPolicy: Never
nameOverride: ""
fullnameOverride: ""
application: datamon-purge

# Tune this for maximum performances
resources: {}

nodeSelector:
  role: platform
tolerations:
  - key: role
    effect: NoSchedule
    operator: Equal
    value: platform
affinity: {}

# you may declare and mount extra volumes on the pod
extraVolumes:
extraVolumeMounts:

extraArgs: []
