{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-credentials"
data:
  '{{ base .Values.credentials }}':
{{ tpl .Values.secret . | b64enc | indent 4 }}
{{- end }}

