apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{.Release.Name}}-staging-claim"
spec:
  storageClassName: {{ .Values.storageClassName }}
  persistentVolumeReclaimPolicy: Delete
  finalizers: []
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stagingSize }}
